name: Ruby Gem

on:
  push:
    tags:        
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@360dc864d5da99d54fcb8e9148c14a84b90d3e88
      with:
        ruby-version: '3.0'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
    - name: Generate man page
      run: bundle exec rake docs
        
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
